services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    azuracom.spresheet_to_object.row_handler:
        class: Azuracom\SpreadsheetToObject\Spreadsheet\Handler

    azuracom.spresheet_to_object.column_type_registry:
        class: Azuracom\SpreadsheetToObject\Registry\ColumnTypeRegistry   

    Azuracom\SpreadsheetToObject\ColumnType\:
        resource: '../../ColumnType'
        tags: ['azuracom_spresheet_to_object.column_type']    

    #aliases
    Azuracom\SpreadsheetToObject\Spreadsheet\HandlerInterface: '@azuracom.spresheet_to_object.row_handler'
    Azuracom\SpreadsheetToObject\Registry\ColumnTypeRegistry: '@azuracom.spresheet_to_object.column_type_registry'