services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    azuracom.spresheet_to_object.row_handler:
        class: Azuracom\SpreadsheetToObject\Spreadsheet\RowHandler

    azuracom.spresheet_to_object.column_type_registry:
        class: Azuracom\SpreadsheetToObject\Registry\ColumnTypeRegistry        

    #aliases
    Azuracom\SpreadsheetToObject\Spreadsheet\RowHandlerInterface: '@azuracom.spresheet_to_object.row_handler'