services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: true

    azuracom.spresheet_to_object.factory.handler:
        class: Azuracom\SpreadsheetToObjectBundle\Factory\HandlerFactory

    azuracom.spresheet_to_object.cell_type_registry:
        class: Azuracom\SpreadsheetToObjectBundle\Registry\CellTypeRegistry   

    Azuracom\SpreadsheetToObjectBundle\CellType\:
        resource: '../src/CellType'
        tags: ['azuracom_spresheet_to_object.cell_type']   

    Azuracom\SpreadsheetToObjectBundle\Twig\:
        resource: '../src/Twig'
        tags: ['twig.extension']  
        
    Azuracom\SpreadsheetToObjectBundle\Form\:
        resource: '../src/Form'
        tags: ['form.type']           

    #aliases
    Azuracom\SpreadsheetToObjectBundle\Factory\HandlerFactoryInterface: '@azuracom.spresheet_to_object.factory.handler'
    Azuracom\SpreadsheetToObjectBundle\Registry\CellTypeRegistry: '@azuracom.spresheet_to_object.cell_type_registry'